source: ./source
destination: ./_site
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: true
encoding: UTF-8
exclude: ["node_modules"]
paginate: 5
paginate_path: "blog/page:num"

latest_cloudify_version: 3.2

github_blueprints_search_query: "-blueprint+in:name+fork:true+user:cloudify-examples"
github_plugins_search_query: "-plugin+in:name+fork:true+user:cloudify-examples"
github_integrations_search_query: "-integration+in:name+fork:true+user:cloudify-examples"

default_examples_version: "master"
default_examples_version_fallback: "master"
examples_cors_proxy: "https://d95fn1u5c9.execute-api.us-west-2.amazonaws.com/prod/proxy"
