source: ./source
destination: ./_site
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: true
encoding: UTF-8
#exclude: ["node_modules"]
#do not commit this exclude part
#exclude:
#  - '_posts'
#  - 'guide' 
#  - 'author_generator'
#end - do not commit this exclude part
paginate: 10
paginate_path: "blog/page:num"
description: Cloudify is an open source application and network orchestration framework based on TOSCA that supports hybrid cloud deployments bridging public and private environments.

latest_cloudify_version: 3.4

gems:
  - jekyll-seo-tag

#Manage Download files:
#-----------------------Change this when new version is up---------------------#
Release_version: 3.4.2~sp-420
Cloudify_version: 3.4.2
Docs_version: 3.4.2
Short_version: 3.4.2
Release: 420
aws_plugin_version: 1.4.4
vcloud_plugin_version: 1.3.1
vsphere_plugin_version: 2.3.0
openstack_plugin_version: 2.0.1
fabric_plugin_version: 1.4.2
diamond_plugin_version: 1.3.5
docker_plugin_version: 1.3.2
psutil_plugin_version: 1.0.2
hostpool_plugin_version: 1.4
gcp_plugin_version: 1.0
azure_plugin_version: 1.4.1
