source: ./source
destination: ./_site
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: true
encoding: UTF-8
exclude: ["node_modules"]
paginate: 5
paginate_path: "blog/page:num"

latest_cloudify_version: 3.2
